services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: 'customers_db'
    ports:
      - '4040:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_URL: '${DB_URL}'
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    restart: always