services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      - '3307:3306'